version: "3.8"

services:
  app1:
    build:
      context: .
    environment:
      NODE_ENV: production
      RESEND_API_KEY: ${RESEND_API_KEY}
      SITE_BASE_URL: ${SITE_BASE_URL}
      AUTH_SECRET: ${AUTH_SECRET}
      DATABASE_URL: ${NEON_DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
    depends_on:
      - redis
    networks:
      - app-network

  app2:
    build:
      context: .
    environment:
      NODE_ENV: production
      RESEND_API_KEY: ${RESEND_API_KEY}
      SITE_BASE_URL: ${SITE_BASE_URL}
      AUTH_SECRET: ${AUTH_SECRET}
      DATABASE_URL: ${NEON_DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
    depends_on:
      - redis
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro # Mount the custom Nginx configuration
    ports:
      - "3000:80" # Expose port 80 from Nginx as 3000 on the host
    depends_on:
      - app1
      - app2
    networks:
      - app-network

  redis:
    image: "redis:alpine"
    ports:
      - "6380:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
